name: toku_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/colors/
    - assets/images/family_members/
    - assets/images/numbers/
    - assets/sounds/colors/
    - assets/sounds/family_members/
    - assets/sounds/numbers/
    - assets/sounds/phrases/
